### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rffontenelle** [lahwaacz/arch-wiki-docs#15]
Error when building `arch-wiki-docs` package, but I'm not sure whether it is on ArchWiki or in the software.

```
$ LC_ALL=C makepkg -fsC
==> Making package: arch-wiki-docs 20170822-1 (Wed Nov 22 21:49:44 -02 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating arch-wiki-docs git repo...
Fetching origin
==> Validating source files with md5sums...
    arch-wiki-docs ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of arch-wiki-docs git repo...
Cloning into 'arch-wiki-docs'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
Available namespaces:
  -2 -- Media
  -1 -- Special
   0 -- Main
   1 -- Talk
   2 -- User
   3 -- User talk
   4 -- ArchWiki
   5 -- ArchWiki talk
   6 -- File
   7 -- File talk
   8 -- MediaWiki
   9 -- MediaWiki talk
  10 -- Template
  11 -- Template talk
  12 -- Help
  13 -- Help talk
  14 -- Category
  15 -- Category talk
Processing namespace 0...
  [downloading] .NET Core
Traceback (most recent call last):
  File "arch-wiki-docs.py", line 31, in <module>
    downloader.process_namespace(ns)
  File "/home/rffontenelle/builds/arch-wiki-docs/src/arch-wiki-docs/ArchWiki/downloader.py", line 87, in process_namespace
    self.cb_download(fullurl, fname)
  File "/home/rffontenelle/builds/arch-wiki-docs/src/arch-wiki-docs/ArchWiki/optimizer.py", line 23, in optimize_url
    self.optimize(urllib.request.urlopen(url), fout)
  File "/home/rffontenelle/builds/arch-wiki-docs/src/arch-wiki-docs/ArchWiki/optimizer.py", line 42, in optimize
    self.fix_footer()
  File "/home/rffontenelle/builds/arch-wiki-docs/src/arch-wiki-docs/ArchWiki/optimizer.py", line 138, in fix_footer
    f_list = self.root.cssselect("#f-list")[0]
IndexError: list index out of range
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by rffontenelle** [comment]
Any idea?

**Comment by lahwaacz** [comment]
Oh yes, sorry for the delay. The [default skin change](https://git.archlinux.org/vhosts/wiki.archlinux.org.git/commit/?id=cc3c61f55eb4d4db2cde861e630e28188e588c1e) broke the script.
